[package]
name = "autorebase"
version = "0.1.0"
authors = ["Tim Hutt <timh@graphcore.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.4"
anyhow = "1.0.40"
colored = "2.0.0"
git_commands = { path = "git_commands" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[dev-dependencies]
# For tests
tempfile = "3.1.0"
